version: "3"
services:
  db:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  app:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env
