version: "3.8"
services:
  app:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: walletwatch_db
      MYSQL_USER: cct
      MYSQL_PASSWORD: cct
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
