version: '3'
services:
  app:
    build: ./
    command: sh -c "sleep 2 && python3 ./walletwatch.py"
    depends_on:
      - db
    env_file: .env
    ports:
      - '5000:5000'
    volumes:
      - walletwatch-app-data:/walletwatch

  db:
    build: ./db/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: walletwatch_db
      MYSQL_USER: cct
      MYSQL_PASSWORD: cctcollege2023*
    ports:
      - '3306:3306'
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - walletwatch-db-data:/var/lib/mysql
volumes:
  walletwatch-db-data:
  walletwatch-app-data:
